version: '3.8'
services:
  churros-backend:
    container_name: churros-backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - MARIADB_PASSWORD=A503
      - MONGODB_URL= "mongodb://churros:A503@churros-mongodb:27017/newsdb"
    ports:
      - "9999:9999"
    restart: always
  churros-crs:
    container_name: churros-crs
    build:
      context: ./recommend/pyrecommend-server
      dockerfile: Dockerfile
    ports:
      - "5555:8000"
networks:
  default:
    name: cd_network
    external: true
