version: '3.8'
services:
  churros-backend:
    container_name: churros-backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - LEE_AN_CHAE=good
    ports:
      - "9999:9999"
    restart: always
  churros-mariadb:
    container_name: churros-mariadb
    build:
      dockerfile: Dockerfile
      context: ./RDBMS
    environment:
      - MARIADB_DATABASE=churros
      - MARIADB_ROOT_PASSWORD=A503
    volumes:
      - ./RDBMS/config:/etc/mysql/conf.d
      - ./RDBMS/data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: no
networks:
  default:
    external:
      name: cd_network
