version: '3.8'
services:
  churros-backend:
    container_name: churros-backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - LEE_AN_CHAE=goo
    ports:
      - "9999:9999"
    restart: always
networks:
  default:
    name: cd_network
    external: true
